### PR TITLE
Add hint about correct HTTP response header

### PR DESCRIPTION
**Pull request by jpawlowski**

### CODE REVIEW

**Comment by kaushalmodi** [comment]
TIL, thanks!

**Comment by kaushalmodi** [comment]
@jpawlowski Btw, I now force the Content Type to be "application/atom+xml" on Netlify, but now opening https://scripter.co/atom.xml even on the latest Firefox prompts me to download it instead of rendering it nicely in the browser.. any hints on how to avoid that download prompt?

**Comment by kaushalmodi** [comment]
Linking this back to the README: https://github.com/kaushalmodi/hugo-atom-feed#pay-attention-to-web-server-mime-type

**Comment by kaushalmodi** [comment]
@jpawlowski Bummer! After setting the content type, I can no longer validate that Atom feed using the w3c validator! https://validator.w3.org/check?uri=https%3A%2F%2Fscripter.co%2Fatom.xml

**Comment by jpawlowski** [comment]
This file being downloaded instead of rendered is actually one of the expected behaviors.
Likely browsers will also start to automatically open your feed reader, depending if your feed reader application actually claimed to handle this particular mime-type. This will improve the end-user experience, developers shall be able to live with this and find workarounds to watch the file in clear text (e.g. using cURL on the terminal).

@kaushalmodi 
about your feed validation issue: Make sure you're not forgetting the correct encoding, otherwise the validator will fall back to latin1 and likely not be able to parse your content properly.

**Pull request merged**
